### ISSUE TITLE
Module 'devicehealth' has failed: disk I/O error

### ISSUE THREAD

**Issue by tomponline** [canonical/microceph#71]
Since https://github.com/canonical/microceph/issues/67 was fixed, I'm starting to see these errors:

```
microceph.ceph -s
  cluster:
    id:     016b1f4a-bbe5-4c6a-aa66-64a5ad9fce7f
    health: HEALTH_ERR
            Module 'devicehealth' has failed: disk I/O error
 
  services:
    mon: 3 daemons, quorum v1,v2,v3 (age 19s)
    mgr: v1(active, since 8s), standbys: v3, v2
    osd: 3 osds: 3 up (since 13s), 3 in (since 6m)
 
  data:
    pools:   1 pools, 1 pgs
    objects: 1 objects, 0 B
    usage:   17 MiB used, 30 GiB / 30 GiB avail
    pgs:     1 active+clean
```

I'm using the demo setup described here:

https://github.com/canonical/microceph/issues/67#issuecomment-1346100403

Can you help me diagnose this please?

Thanks

**Comment by jonnypeace** [comment]
I tried starting a new ceph cluster today, and this is the same error i'm seeing.

**Comment by stgraber** [comment]
Looks like I got this one sorted out now.

**Comment by tomponline** [comment]
Thanks!

**Comment by chengzhidada** [comment]
My friend, how did you solve this problem？

**Comment by KlavsKlavsen** [comment]
yes.. was a fix merged in some version of ceph or ?

**Comment by UtkarshBhatthere** [comment]
Hey @KlavsKlavsen @chengzhidada this was caused by stale socket files fixed in #69. If you still get this issue from a recent microceph release (`reef` channel) please create a new issue with logs from your microceph deployment.

**Comment by ACK-lcn** [comment]
Hello, my CEPH version is 17.2.4, and there is currently an issue with the "Module 'devicehealth' has failed: disk I/O error" issue you mentioned earlier. How did you fix it? Did you upgrade to the new version?

**Comment by LongTengYiFei** [comment]
I meet the same problem, my ceph-mgr log is:
```
2024-12-19T08:06:35.743+0000 7f81870d4640 -1 devicehealth.serve:
2024-12-19T08:06:35.743+0000 7f818f0e4640  0 [restful DEBUG root] setting log level based on debug_mgr: INFO (2/5)
2024-12-19T08:06:35.743+0000 7f818f0e4640  1 mgr load Constructed class from module: restful
2024-12-19T08:06:35.743+0000 7f817d7c1640  0 [rbd_support INFO root] MirrorSnapshotScheduleHandler: load_schedules
2024-12-19T08:06:35.743+0000 7f817bfbe640  0 [restful INFO root] server_addr: :: server_port: 8003
2024-12-19T08:06:35.743+0000 7f817afbc640  0 [rbd_support INFO root] MirrorSnapshotScheduleHandler: starting
2024-12-19T08:06:35.743+0000 7f818f0e4640  0 [status DEBUG root] setting log level based on debug_mgr: INFO (2/5)
2024-12-19T08:06:35.743+0000 7f818f0e4640  1 mgr load Constructed class from module: status
2024-12-19T08:06:35.743+0000 7f8179fba640  0 [rbd_support INFO root] PerfHandler: starting
2024-12-19T08:06:35.747+0000 7f818f0e4640  0 [telemetry DEBUG root] setting log level based on debug_mgr: INFO (2/5)
2024-12-19T08:06:35.747+0000 7f818f0e4640  1 mgr load Constructed class from module: telemetry
2024-12-19T08:06:35.747+0000 7f817bfbe640  0 [restful WARNING root] server not running: no certificate configured
2024-12-19T08:06:35.743+0000 7f81870d4640 -1 Traceback (most recent call last):
  File "/usr/local/share/ceph/mgr/devicehealth/module.py", line 338, in serve
    if self.db_ready() and self.enable_monitoring:
  File "/usr/local/share/ceph/mgr/mgr_module.py", line 1223, in db_ready
    return self.db is not None
  File "/usr/local/share/ceph/mgr/mgr_module.py", line 1235, in db
    self._db = self.open_db()
  File "/usr/local/share/ceph/mgr/mgr_module.py", line 1216, in open_db
    self.configure_db(db)
  File "/usr/local/share/ceph/mgr/mgr_module.py", line 1198, in configure_db
    db.execute('PRAGMA JOURNAL_MODE = PERSIST')
sqlite3.OperationalError: disk I/O error
```
I solve it, close ceph-mgr, delete the .mgr pool, and restart the ceph-mgr.
Then, the .mgr pool will be created automatically.
`ceph osd pool rm .mgr .mgr --yes-i-really-really-mean-it`
The link I referenced is 
> https://cray-hpe.github.io/docs-csm/en-16/operations/utility_storage/troubleshoot_health_err_module_devicehealth/
